#- load ip_vs iptables and ipset modules

- name: Deploy Routers LBs | make sure modules are loaded at boot   
  template:
    src: keepalived-pod.conf
    dest: /etc/modules-load.d/keepalived-pod.conf
    
- name: Deploy Routers LBs | make sure ip_vs is loaded
  modprobe:
    name: ip_vs
    state: present

- name: Deploy Routers LBs | make sure ipset is loaded
  modprobe:
    name: ip_set
    state: present     

- name: Deploy Routers LBs | install python-firewall
  package:
    name: python-firewall
    state: present   
    
- name: Deploy Routers LBs | install firewalld
  package:
    name: firewalld
    state: present
  when: os_firewall_use_firewalld         

- name: Deploy Routers LBs | open VRRP port
  firewalld:
    rich_rule: 'rule protocol value="vrrp" accept'
    permanent: true
    state: enabled
    immediate: true
  when: os_firewall_use_firewalld    
    
- name: Deploy Routers LBs | open VRRP port - iptables
  iptables: 
    chain: INPUT
    protocol: vrrp
    jump: ACCEPT
  when: not os_firewall_use_firewalld
  
- name: Deploy Routers LBs | reload iptables
  service:
    name: iptables
    state: restarted
  when: not os_firewall_use_firewalld
  
- name: Deploy Routers LBs | 'Enable IP forwading'
  lineinfile: 
    path: /etc/sysctl.d/50-keepalived.conf
    regexp: '^net.ipv4.ip_forward.*'
    line: 'net.ipv4.ip_forward=1'
    create: yes
    state: present
    owner: root
    group: root
    mode: 0644

- name: Deploy Routers LBs | 'reload sysctl'
  command: sysctl -p       
    
- name: Deploy Routers LBs | make sure conf dir is present
  file:
    name: "{{ static_pod_config_path }}"
    state: directory    
    
- name: Deploy Routers LBs | create routers keepalived configuration
  template:
    src: routers-keepalived.conf.j2
    dest: "{{ static_pod_config_path }}/routers-keepalived.conf"

- name: Deploy Routers LBs | make sure pod dir is present
  file:
    name: "{{ static_pod_manifest_path }}"
    state: directory

- name: Deploy Routers LBs | create routers keepalived pod definition    
  template:
    src: routers-keepalived-pod.yaml.j2
    dest: "{{ static_pod_manifest_path }}/routers-keepalived-pod.yaml"
    