---
- hosts: 
    - masters
    - infras
    - nodes
    - masters-lbs
    - routers-lbs
  gather_facts: true

- name: OCP Hosts, Handle Prereqs
  hosts:
    - masters
    - infras
    - nodes
    - masters-lbs
    - routers-lbs
  gather_facts: true
  become: yes
  tasks:
    - name: Handle OCP Prereqs
      include_role:
        name: ocp-prereqs