---
# - hosts: all
#   gather_facts: true

- name: OCP CNS Deployer
  hosts: glusterfs
  gather_facts: true
  tasks:
    - name: Deploy CNS on OCP
      include_role:
        name: container-native-storage