---
- name: YUM Nutanix Deployer
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Provision Ansible Tower on Nutanix
      include_role:
        name: nutanix_provisioner
      vars:
        vm_defs: "{{ vm_defs_tower }}"
      tags:
        - provision

    - name: Refresh inventory after provisioning
      meta: refresh_inventory

# Deploy ansible private key to VM
- name: Ansible private key
  hosts: tower_nodes,tower_db_nodes
  remote_user: ansible
  become: yes
  tasks:
    - name: Deploy private key to server
      copy:
        content: "{{ ansible_ssh_private_key }}"
        dest: /home/ansible/.ssh/id_rsa
        owner: ansible
        group: ansible
        mode: 0600

- name: Install Highly Available Ansible Tower
  hosts: tower_nodes
  remote_user: ansible
  become: yes
  tasks: 
    - name: Install Ansible Tower
      include_role:
        name: tower_prelim
