---
# Deploy the VM
- name: YUM Nutanix Deployer
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Provision YUM Repository on Nutanix
      include_role:
        name: nutanix_provisioner
      vars:
        vm_defs: "{{ vm_defs_repo }}"
      tags:
        - provision

    - name: Refresh inventory after provisioning
      meta: refresh_inventory

# Deploy ansible private key to VM
- name: Ansible private key
  hosts: repository
  remote_user: ansible
  become: yes
  tasks:
    - name: Deploy private key to server
      copy:
        content: "{{ ansible_ssh_private_key }}"
        dest: /home/ansible/.ssh/id_rsa
        owner: ansible
        group: ansible
        mode: 0600
    
# Configure the VM
- name: YUM Nutanix Configuration
  hosts: repository
  remote_user: ansible
  become: yes
  vars_prompt:
    - name: "rhsm_username"
      prompt: "RHSM Username"
    - name: "rhsm_password"
      prompt: "RHSM Password"

  tasks:
    - name: Configure using the repository role
      include_role:
        name: repository
      vars:
        repo_rhsm_user: "{{ rhsm_username }}"
        repo_rhsm_password: "{{ rhsm_password }}"
