---
- name: OCP VMs Provisioner
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Provision OpenShift VMs on Nutanix
      include_role:
        name: nutanix_provisioner
      vars:
        vm_defs: "{{ vm_defs_ocp }}"
      tags:
        - provision

    - name: Refresh inventory after provisioning
      meta: refresh_inventory
# Deploy ansible private key to VM
- name: Ansible private key
  hosts: tower
  remote_user: ansible
  become: yes
  tasks:
    - name: Deploy private key to server
      copy:
        content: "{{ ansible_ssh_private_key }}"
        dest: /home/ansible/.ssh/id_rsa
        owner: ansible
        group: ansible
        mode: 0600
    - name: Install ntpd
      yum:
        name: "ntp"
        state: "latest"
    - name: Configure ntp server
      template:
        src:  "ntp.conf.j2"
        dest: "/etc/ntp.conf"
    - name: Disable chrony
      service:
        name: "chronyd"
        state: stopped
        enabled: false
    - name: Start/enable ntpd
      service:
        name: "ntpd"
        state: started
        enabled: true

- hosts: nodes
  gather_facts: true

- name: OCP Hosts, Handle Prereqs
  hosts:
    - nodes
  gather_facts: true
  become: yes
  tasks:
    - name: Handle OCP Prereqs
      include_role:
        name: ocp_prereqs
      tags:
       - install

- name: Configure masters for CNS deployment
  hosts: masters
  gather_facts: true
  tasks:
    - name: Install required CNS packages on OCP Masters
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - cns-deploy
        - heketi-client

    - name: Disable the gluster repos for all Masters
      yum_repository:
        name: local_server_gluster
        state: absent
