---
- name: OCP VMs Provisioner
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Provision OpenShift VMs on Nutanix
      include_role:
        name: nutanix_provisioner
      vars:
        vm_defs: "{{ vm_defs_ocp }}"
      tags:
        - provision

    - name: Refresh inventory after provisioning
      meta: refresh_inventory


- hosts: all
  gather_facts: true



- name: OCP Hosts, Handle Prereqs
  hosts:
    - nodes
  gather_facts: true
  become: yes
  tasks:
    - name: Handle OCP Prereqs
      include_role:
        name: ocp-prereqs
      tags:
       - install

- name: Configure masters for CNS deployment
  hosts: masters
  gather_facts: true
  tasks:
#    - name: Enable the gluster repos for all Masters
#      yum_repository:
#        name: local_server_gluster
#        state: present
#        baseurl: "http://repository.{{ vm_net_domain }}/repos/yum/rh-gluster-3-client-for-rhel-7-server-rpms"
#        description: local_server_gluster
#        gpgcheck: no

    - name: Install required CNS packages on OCP Masters
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - cns-deploy
        - heketi-client

    - name: Disable the gluster repos for all Masters
      yum_repository:
        name: local_server_gluster
        state: absent
