---
# handlers file for loadbalancer_ha

- name: reload_sysctl
  command: sysctl -p

- name: restart_keepalived
  service:
    name: keepalived
    state: restarted

- name: restart_haproxy
  service:
    name: haproxy
    state: restarted

- name: restart_rsyslog
  service:
    name: rsyslog
    state: restarted

- name: reload_systemctl
  systemd:
    daemon_reload: yes
