---
# Control debug level

test:
  - vm_name: "gen_test_1"
    vm_cpu_sockets: 4
    vm_cpu_per_socket: 1
    vm_ram: 16384
    vm_disk_list:
      - disk_size_mib: 100000
      - disk_size_mib: 50000
      - disk_size_mib: 50000
    vm_ip: 172.29.171.99