--- 
- name: Deploy Loadbalancers | install-haproxy | enable and start or reload firewalld
  service:
    name: firewalld
    state: reloaded
    enabled: yes

- name: Deploy Loadbalancers | install-haproxy | Open Firewall for HAproxy use
  firewalld: 
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  with_items: "{{ ports }}"

- name: Deploy Loadbalancers | install-haproxy | Enable syslog logging
  copy:
    src: rsyslog_haproxy.conf
    dest: /etc/rsyslog.d/haproxy.conf
  notify: 'restart rsyslog'

- name: Deploy Loadbalancers | install-haproxy |  install haproxy
  yum:
    name: haproxy
    state: present
  
- name: Deploy Loadbalancers | install-haproxy |  deploy haproxy config file
  template:
    src: "{{ haproxy_template }}"
    dest: "/etc/haproxy/haproxy.cfg"
    validate: 'haproxy -c -f %s'     
  notify: 'enable and start or reload haproxy'