- name: LBs Prereqs | rhn_registration | Register host to the Red Hat Network (RHN)
  redhat_subscription:
    state: present
    username: "{{ rhn_user }}"
    password: "{{ rhn_password }}"
    autosubscribe: false
  register: task_result
  until: task_result is succeeded
  retries: 10
  delay: 5
  tags:
    - register

# Pull SKU from available subscription pool (Openshift)
- name: OCP Prereqs | rhn_registration | Search for available OpenShift subscription
  shell: /usr/bin/subscription-manager list --all --available --matches "RHEL*" --matches "Employee*"| awk '/Pool ID/ {print $3}' | head -1
  # shell: /usr/bin/subscription-manager list --available --matches "*OpenShift*"
  register: pool_id_employee
  ignore_errors: yes
  tags:
    - register

- debug:
    var: pool_id_employee
  when: global_debug

# Attaching host to Pool ID from above
- name: LBs Prereqs | rhn_registration | Attach machine to Pool ID (RHEL)
  command: /usr/bin/subscription-manager attach --pool={{ pool_id_employee.stdout }}
  register: task_result
  until: task_result.rc == 0
  retries: 10
  delay: 1
  any_errors_fatal: true
  tags:
    - register