- name: register using subscription-manager
  redhat_subscription:
    state: present
    username: "{{ repo_rhsm_user }}"
    password: "{{ repo_rhsm_password }}"

- name: get the proper ocp pool id
  shell: /usr/bin/subscription-manager list --all --available --matches="*OpenShift Container*" | awk '/Pool ID/ {print $3}' | head -1
  register: ocppool

- name: has the ocp pool id already been attached?
  shell: /usr/bin/subscription-manager list --installed
  register: ocppoolinstalled

- name: register using subscription-manager with ocp pool id
  redhat_subscription:
    state: present
    username: "{{ repo_rhsm_user }}"
    password: "{{ repo_rhsm_password }}"
    pool: "{{ ocppool.stdout }}"
  when: ocppoolinstalled.stdout is not search("OpenShift Container") 

- name: does the system have the proper repos enabled?
  shell: subscription-manager repos --list-enabled
  register: ocprepostatus

- name: disable all repos if this is a first run
  shell: subscription-manager repos --disable='*'
  when: ocprepostatus.stdout is not search("rhel-7-server-ose")

- name: attach proper repos
  shell: "subscription-manager repos --enable={{ item }}"
  with_items:
    - "{{ repo_enabled_repositories }}"
  when: ocprepostatus.stdout is not search("rhel-7-server-ose")
