- name: Create a basic VM (test1)
  uri:
    url: "{{ api_v3 }}/vms"
    # body: "{{ lookup('file','vm-def.json') }}"
    # Probably best to move this into a template for reusability
    body:
      api_version: '3.0'
      metadata:
        kind: vm
      spec:
        cluster_reference:
          kind: cluster
          uuid: "{{ cluster_uuid }}"
        name: automation-test-1
        resources:
          memory_size_mib: 1024
          nic_list:
          - subnet_reference:
              kind: subnet
              uuid: "{{ subnet_uuid }}"
          # - ip_endpoint_list:
          #     - ip: "172.29.171.200" #Specifying the IP here results in successful API call with no vm created?
          #     - type: ASSIGNED
          disk_list:
          - data_source_reference:
              kind: image
              uuid: "{{ rhel_binary_dvd_iso }}"
            device_properties:
              device_type: CDROM
          - disk_size_mib:
              38147 #40GB
          - disk_size_mib:
              1024 #~10GB
          - disk_size_mib:
              1024 #~10GB
          num_sockets: 1
          num_vcpus_per_socket: 1
          power_state: 'ON'
          guest_customization:
             cloud_init:
               user_data: "{{ lookup('template','cloud-init') | b64encode }}"
    method: POST
    validate_certs: no
    body_format: json
    headers: 
      Cookie: "{{ session_cookie }}"
    status_code: 202
  register: json_create_result

- name: Display vm creation response
  debug:
    var: json_create_result.json
  when: global_debug

- name: Register the task uuid so we can reference this VM directly later
  set_fact:
    test_vm_uuid_1: "{{ json_create_result.json.metadata.uuid }}"

- debug:
    var: test_vm_uuid_1
