---
# tasks file for nutanix_provisioner
- include: get_session_cookie.yml

# Collect uuids needed for VM provisioning
- include: get_cluster_uuids.yml
- include: get_subnet_uuids.yml
- include: get_image_uuids.yml
- include: define_uuids_from_names.yml



# - include: provision_vm.yml

- name: Debug | list test_vms variable
  debug: 
    msg: "{{ groups | list }}"


- name: Provision Test VMs
  debug:
    msg: "{{ hostvars[item] }}"
  loop: "{{ groups['test'] }}"


  


# Loop to provision master VMs


# Loop to provision infrastructure VMs


# Loop to provision worker VMs


# - include:  provision_lbs.yml
#   when: deploy_openshift

# - include:  provision_masters.yml
#   when: deploy_openshift

# - include:  provision_infras.yml
#   when: deploy_openshift

# - include:  provision_nodes.yml
#   when: deploy_openshift
