- set_fact:
    vm_body: "{{ lookup('template', 'vm-body.yml.j2') | from_yaml }}"

- debug:
    var: vm_body
  when: global_debug

- name: Create a basic VM
  uri:
    url: "{{ api_url_v3 }}/vms"
    body:
      "{{ vm_body }}"
    method: POST
    validate_certs: no
    body_format: json
    headers: 
      Cookie: "{{ session_cookie }}"
    status_code: 202
  register: json_create_result

- name: Display vm creation response
  debug:
    var: json_create_result.json | to_yaml
  when: global_debug

- name: Register the vm uuid so we can reference this VM directly later
  set_fact:
    test_vm_uuid_1: "{{ json_create_result.json.metadata.uuid }}"

- debug:
    var: test_vm_uuid_1
  when: global_debug
