---=
- name: Provisioning | Create OpenShift App Nodes
  uri:
    url: "{{ api_v3 }}/vms"
    body: "{{ lookup('file','vm-def.json') }}"
    method: POST
    validate_certs: no
    force_basic_auth: no
    body_format: json
    headers: 
      Cookie: "{{ session_cookie }}"
    status_code: 202
  register: json_create_result

- name: Provisioning | Display vm creation response
  debug:
    var: json_create_result
  when: global_debug

- set_fact:
    node1_uuid: "{{ json_create_result.json.metadata.uuid }}"