---
# The following was adapted from:
# https://access.redhat.com/documentation/en-us/container-native_storage/3.9/html-single/container-native_storage_for_openshift_container_platform/index#chap-Documentation-Red_Hat_Gluster_Storage_Container_Native_with_OpenShift_Platform-RHGS_Container_Converged_with_OS


- name: Container Native Storage | install cns packages on the cluster
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ cns_packages }}"

- name: Container Native Storage | Setup multipath (CNS reqs)
  command: mpathconf --enable
  when: inventory_hostname in groups.glusterfs

- name: Container Native Storage | Template out the multipath.conf file
  template:
    src: multipath.conf.j2
    dest: /etc/multipath.conf
  when: inventory_hostname in groups.glusterfs

- name: Container Native Storage | Restart the multipathd service
  service:
    name: multipathd
    state: restarted
  when: inventory_hostname in groups.glusterfs

- name: Container Native Storage | Set iptables rules for gluster connections
  lineinfile:
    path: /etc/sysconfig/iptables
    state: present
    line: "{{ item }}"
    insertbefore: '^COMMIT'
  loop: "{{ ip_tables_rules }}"
  when: inventory_hostname in groups.glusterfs

- name: Container Native Storage | Reload iptables
  become: yes
  shell: iptables-restore <  /etc/sysconfig/iptables

- name: Container Native Storage | Load kernel modules for CNS
  modprobe:
    name: "{{ item }}"
    state: present
  loop: "{{ mod_probe_list }}"
  when: inventory_hostname in groups.glusterfs

- name: Container Native Storage | Persist kernel modules across reboots
  lineinfile:
    path: /etc/modules-load.d/dm_thin_pool.conf
    state: present
    line: dm_thin_pool
    create: yes
  when: inventory_hostname in groups.glusterfs

- name: Container Native Storage | Persist kernel modules across reboots
  lineinfile:
    path: /etc/modules-load.d/dm_multipath.conf
    state: present
    line: dm_multipath
    create: yes
  when: inventory_hostname in groups.glusterfs

- name: Container Native Storage | Persist kernel modules across reboots
  lineinfile:
    path: /etc/modules-load.d/target_core_user.conf
    state: present
    line: target_core_user
    create: yes
  when: inventory_hostname in groups.glusterfs

- name: Container Native Storgage | Set rpcbind service options
  command: systemctl add-wants multi-user rpcbind.service
  when: inventory_hostname in groups.glusterfs

- name: Container Native Storage | Enable rpcbind.service
  service:
    name: rpcbind
    state: restarted
    enabled: yes
  when: inventory_hostname in groups.glusterfs

