---

- name: 'reload sysctl'
  command: sysctl -p

- name: 'enable and start or reload keepalived'
  service:
    name: keepalived
    state: reloaded
    enabled: yes  
    
- name: 'enable and start or reload haproxy'
  service:
    name: haproxy
    state: reloaded
    enabled: yes    

- name: 'restart rsyslog'
  service:
    name: rsyslog
    state: restarted