---
- name: Ensure Ansible is installed on nodes
  yum:
    name: ansible
    state: present

- name: Download Ansible Tower tarball
  get_url:
    url: "{{ tower_artifact_url }}"
    dest: "{{ tower_install_dir }}/{{ tower_tar_name }}"
    owner: "{{ tower_install_user }}"
    group: "{{ tower_install_group }}"
  when: inventory_hostname in groups['tower_nodes'] | first

- name: Unpack Ansible Tower tarball
  unarchive:
    src: "{{ tower_install_dir }}/{{ tower_tar_name }}"
    dest: "{{ tower_install_dir }}"
    remote_src: yes 
  when: inventory_hostname in groups['tower_nodes'] | first

- name: Copy custom inventory file for installation 
  template:
    src: "inventory_cluster.j2"
    dest: "{{ tower_install_dir }}/{{ tower_install_folder }}/inventory_custom"
    owner: "{{ tower_install_user }}"
    group: "{{ tower_install_group }}"
    force: yes
  when: inventory_hostname in groups['tower_nodes'] | first

- name: Copy custom installation script
  copy:
    src: files/ansible_tower_custom.sh
    dest: "{{ tower_install_dir }}/{{ tower_install_folder }}"
    owner: "{{ tower_install_user }}"
    group: "{{ tower_install_group }}"
    mode: 0755 
  when: inventory_hostname in groups['tower_nodes'] | first

- name: Run custom installation script
  shell: "./ansible_tower_custom.sh"
  args:
    chdir: "{{ tower_install_dir }}/{{ tower_install_folder }}"
  when: inventory_hostname in groups['tower_nodes'] | first

- name: Add EULA acceptance
  lineinfile:
    path: files/license.txt
    regexp: '^{'
    insertafter: '^{'
    line: '{ "eula_accepted" : "true",'
  when: inventory_hostname in groups['tower_nodes'] | first

- name: Post license to Ansible Tower
  uri:
    url: "https://{{ inventory_hostname }}.{{ vm_net_domain }}/api/v2/config/"
    method: POST
    user: "{{ admin_tower_user }}"
    password: "{{ admin_tower_pw }}"
    body: "{{ lookup('file', '{{ tower_license }}') }}"
    force_basic_auth: yes
    status_code: 200
    body_format: json
    validate_certs: false
  when: inventory_hostname in groups['tower_nodes'] | first
 