---
- name: Configure OCP to talk to Quay
  hosts: masters
  become: yes
  tasks:
    - name: Add quay as an insecure registry
      lineinfile:
        path: /etc/sysconfig/docker
        line: "INSECURE_REGISTRY='--insecure-registry={{ quay_hostname }}'"
      
    - name: Restart docker
      service:
        name: docker
        state: restarted

- name: Set up OCP secret for quay
  hosts: masters
  become: yes
  tasks:
    - name: Create OCP secret for quay
      command: "oc create secret docker-registry quay-pull-secret --docker-server=https://{{ quay_hostname }} --docker-username={{ quay_superuser_username }} --docker-password={{ quay_superuser_password }} --docker-email={{ quay_superuser_email }}"
      run_once: true

    - name: Link OCP secret to permissions
      command: "oc secrets link default quay-pull-secret --for=pull,mount"
      run_once: true