---
- name: Create a new OpenShift Admin Account
  hosts: masters
  become: yes
  tasks:
    - name: Use HTPasswd to create account
      htpasswd:
        name: "{{ item  }}"
        password: "SOCsif123!@#"
        path: /etc/origin/master/htpasswd
      with_items:
        - admin
   
- name: Add proper Cluster Roles
  hosts: labs-ocp-master-01.ocplabs.dell.local
  become: yes
  tasks:
    - name: Add ADMIN role
      command: "oadm policy add-cluster-role-to-user cluster-admin {{ item }}"
      with_items:
        - admin
