---
- name: Create a new OpenShift Admin Account
  hosts: masters
  become: yes
  tasks:
    - name: Use HTPasswd to create account
      htpasswd:
        name: "{{ item  }}"
        password: "somerandompasswordyoushouldchange"
        path: /etc/origin/master/htpasswd
      with_items:
        - admin
        - matt
   
- name: Add proper Cluster Roles
  hosts: masters
  become: yes
  tasks:
    - name: Add ADMIN role
      command: "oadm policy add-cluster-role-to-user cluster-admin {{ item }}"
      with_items:
        - admin
        - matt
      run_once: true
