---
- name: Create a new OpenShift Admin Account
  hosts: masters
  become: yes
  tasks:
    - name: Install python-passlib
      yum:
        name: python-passlib
        state: present

    - name: Use HTPasswd to create account
      htpasswd:
        name: "{{ item  }}"
        password: "{{ ocp_password }}"
        path: /etc/origin/master/htpasswd
      with_items:
        - mbach
   
- name: Add proper Cluster Roles
  hosts: ocp-master-01.ocp.dell.local
  become: yes
  tasks:
    - name: Add ADMIN role
      command: "oc adm policy add-cluster-role-to-user cluster-admin {{ item }}"
      with_items:
        - mbach
