---
- name: Create a new OpenShift Admin Account
  hosts: masters
  become: yes
  tasks:
    - name: Install python-passlib
      yum:
        name: python-passlib
        state: present

    - name: Use HTPasswd to create account
      htpasswd:
        name: "{{ item  }}"
        password: somerandompasswordyoushouldchange
        path: /etc/origin/master/htpasswd
      with_items:
        - carolyn
        - matt
        - tim
   
- name: Add proper Cluster Roles
  hosts: labs-ocp-master-01.ocplabs.dell.local
  become: yes
  tasks:
    - name: Add ADMIN role
      command: "oadm policy add-cluster-role-to-user cluster-admin {{ item }}"
      with_items:
        - tim
        - carolyn
        - matt
