---
- name: Create a new OpenShift account for SGE developers
  hosts: masters
  become: yes
  tasks:
    - name: Install python-passlib
      yum:
        name: python-passlib
        state: present

    - name: Use HTPasswd to create account
      htpasswd:
        name: "{{ item  }}"
        password: somerandompasswordyoushouldchange
        path: /etc/origin/master/htpasswd
      with_items:
        - carolyn-test
        - martin
        - brendan
   
- name: Add admin role for developers
  hosts: labs-ocp-master-01.ocplabs.dell.local
  become: yes
  tasks:
    - name: Create sge-dev project
      command: "oc new-project sge-dev"

    - name: Add ADMIN role
      command: "oadm policy add-role-to-user admin {{ item }} -n sge-dev"
      with_items:
        - carolyn-test
        - martin
        - brendan

    - name: Add SELF-PROVISIONER role
      command: "oadm policy add-role-to-user self-provisioner {{ item }}"
      with_items:
        - carolyn-test
        - martin
        - brendan
